# Generated by Django 2.2 on 2022-10-24 14:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20221022_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nickname', unique=True),
        ),
    ]
